create table if not exists public.favorite_products (
  id bigint generated by default as identity primary key,
  app_user_id bigint not null,
  product_id bigint not null,
  product_name text not null,
  product_img_url text,
  product_price numeric(10, 2) not null,
  created_at timestamptz not null default now(),
  constraint favorite_products_user_product_unique unique (app_user_id, product_id)
);

alter table public.favorite_products enable row level security;

grant select, insert, update, delete on public.favorite_products to anon;
grant usage, select on sequence public.favorite_products_id_seq to anon;

drop policy if exists "Public can read favorites for mobile test" on public.favorite_products;
drop policy if exists "Public can insert favorites for mobile test" on public.favorite_products;
drop policy if exists "Public can update favorites for mobile test" on public.favorite_products;
drop policy if exists "Public can delete favorites for mobile test" on public.favorite_products;

create policy "Public can read favorites for mobile test"
on public.favorite_products
for select
to anon
using (true);

create policy "Public can insert favorites for mobile test"
on public.favorite_products
for insert
to anon
with check (true);

create policy "Public can update favorites for mobile test"
on public.favorite_products
for update
to anon
using (true)
with check (true);

create policy "Public can delete favorites for mobile test"
on public.favorite_products
for delete
to anon
using (true);
